#!/bin/bash -x

export PATH=/usr/local/bin:/usr/bin:/bin

scheme --load sum.scm < /dev/null
#scheme --load sumtail.scm < /dev/null

# Scheme's idea of native-code compilation.
#scheme --eval '(cf "sum")' < /dev/null
#scheme --load sum < /dev/null
